import React from 'react';
import {Boxes,Cpu,Database,HardDrive,MemoryStick,Network,Package,Server,Tags,Wifi} from 'lucide-react';
import {platformInfo,pct,safe,uptime,ramTotalLabel,loxberryVersion} from '../shared/utils';

function Badge({children,type='ok'}){return <span className={'badge '+type}>{children}</span>}
function MetricBar({label,value,type='blue'}){const n=pct(value);return <div className="metric-line"><div className="metric-top"><span>{label}</span><strong>{n===null?'-':`${n}%`}</strong></div><div className="mini-bar"><i className={type} style={{width:`${n===null?0:Math.min(100,n)}%`}}/></div></div>}
function EmptyModule({icon,title,children}){return <section className="panel module-panel"><div className="module-icon">{icon}</div><div><h2>{title}</h2><p className="muted">{children}</p></div></section>}
function Spark(){return <svg className={'spark blue'} viewBox="0 0 120 40" preserveAspectRatio="none"><polyline points="0,20 10,17 18,19 28,24 38,18 48,28 58,21 70,23 82,12 92,22 104,16 120,20" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/></svg>}

export default function DeviceDetail({device,full=false}){
 const d=device,m=d.metrics||{},p=platformInfo(d),apps=d.apps||[],containers=m.docker?.containers||[],disks=m.disks||[];
 return <section className="panel detail-panel device-detail-drawer"><div className="panel-head"><div><h2>{d.name||d.serial} <Badge type={d.status==='online'?'ok':d.status==='stale'?'warn':'off'}>{d.status}</Badge></h2><p>Laatst gezien: {d.last_seen?new Date(d.last_seen).toLocaleString():'-'} · {d.serial}</p></div></div><div className="detail-grid"><article><h3><Server size={17}/> Hardware platform</h3><div className="platform-large"><strong>{p.name}</strong><span>{p.model}</span><small>{p.type}</small></div><dl><dt>Model</dt><dd>{safe(d.model)}</dd><dt>Board</dt><dd>{safe(m.board_model)}</dd><dt>Machine</dt><dd>{safe(m.machine)}</dd><dt>CPU cores</dt><dd>{safe(m.cpu_count)}</dd><dt>RAM totaal</dt><dd>{ramTotalLabel(d)}</dd></dl></article><article><h3><Database size={17}/> OS & firmware</h3><dl><dt>OS</dt><dd>{safe(m.os_pretty_name||m.platform)}</dd><dt>DietPi</dt><dd>{safe(m.dietpi_version)}</dd><dt>LoxBerry</dt><dd>{safe(loxberryVersion(d))}</dd><dt>Firmware</dt><dd>{safe(d.firmware)}</dd><dt>Agent versie</dt><dd>{safe(d.agent_version||m.agent_version)}</dd></dl></article><article><h3><Cpu size={17}/> CPU</h3><strong className="big">{pct(d.cpu_percent)??'-'}%</strong><Spark/><MetricBar label="Gebruik" value={d.cpu_percent}/></article><article><h3><MemoryStick size={17}/> RAM</h3><strong className="big">{pct(d.mem_percent)??'-'}%</strong><MetricBar label="RAM" value={d.mem_percent} type="green"/><p className="muted">Totaal {ramTotalLabel(d)}</p></article><article><h3><HardDrive size={17}/> Diskspace</h3><strong className="big">{pct(d.disk_percent)??'-'}%</strong><MetricBar label="Root" value={d.disk_percent} type="amber"/>{disks.slice(0,6).map(x=><p className="app-pill" key={x.mountpoint}><HardDrive size={14}/>{x.mountpoint}: {x.used_gb}/{x.total_gb} GB</p>)}</article><article><h3><Wifi size={17}/> Network</h3><dl><dt>IP</dt><dd>{safe(d.ip_address)}</dd><dt>Hostname</dt><dd>{safe(d.hostname||m.hostname)}</dd><dt>ZeroTier node</dt><dd>{safe(d.zerotier_node_id||m.zerotier?.node_id)}</dd><dt>Uptime</dt><dd>{uptime(m.uptime_seconds)}</dd></dl></article><article><h3><Boxes size={17}/> Apps ({apps.length})</h3>{apps.map(a=><p className="app-pill" key={a}><Boxes size={14}/>{a}</p>)}</article><article><h3><Package size={17}/> Containers ({containers.length})</h3>{containers.slice(0,10).map(c=><p className="app-pill" key={c.id||c.name}><Boxes size={14}/>{c.name}</p>)}</article></div>{full&&<EmptyModule icon={<Tags/>} title="Tags & groups">Device tags, groepen, klantmapping en sitefilters.</EmptyModule>}</section>
}
